spring:
  application:
    name: SpringBoot3Server
  #配置数据源
  datasource:
    #MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/foleable?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

flowable:
  # 开启定时任务JOB
  async-executor-activate: true
  # 在引擎启动时，会自动更新数据库架构
  database-schema-update: true